// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CaseConverter
{
    internal sealed partial class Vsix
    {
        public const string Id = "CaseConverter.8fb08d51-1660-47c6-8b6c-85827895a54e";
        public const string Name = "CaseConverter";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vinay Saini";
        public const string Tags = "";
    }
}
