// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CaseConverter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CaseConverterString = "a7df8fb1-98b7-405f-9f00-d54f963177b3";
        public static Guid CaseConverter = new Guid(CaseConverterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditMenu = 0x0001;
        public const int CTXT_CODEWIN_GRP = 0x0002;
        public const int MenuGroup = 0x0100;
        public const int ToUpper = 0x0201;
        public const int ToLower = 0x0202;
        public const int ToCamel = 0x0203;
        public const int ToPascal = 0x0204;
        public const int Visibility = 0x0301;
    }
}